
server.port=8080

#File Configurations
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

project.image=images/

logging.level.org.springframework.security=DEBUG

springdoc.packagesToScan=com.amancode.blogappserver.Controllers
springdoc.pathsToMatch=/api/v1/auth/**, /api/users/**, /api/categories/**, /api/**

#email smtp setup
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amanwasti5@gmail.com
spring.mail.password=kwwoexfiajuazftx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SPRING AI SETUP OLLAMA
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.chat.options.temperature=0.7

spring.profiles.active=${ENV:dev}